name: monitoring

services:
  loki:
    image: grafana/loki:3.3.0
    container_name: loki
    restart: unless-stopped
    env_file: .env
    ports:
      - ${LOKI_PORT}:3100
    volumes:
      - ./loki.yaml:/etc/loki/loki.yaml
      - loki-data:/loki
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: unless-stopped
    env_file: .env
    expose:
      - 9100
    command:
      - "--path.rootfs=/host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    restart: unless-stopped
    env_file: .env
    depends_on:
      node-exporter:
        condition: service_healthy
    expose:
      - 9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  grafana:
    image: grafana/grafana-oss:11.3.1
    container_name: grafana
    restart: unless-stopped
    env_file: .env
    depends_on:
      loki:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana-metrics-dashboard.json:/var/lib/grafana/dashboards/metrics.json
      - ./grafana-logs-dashboard.json:/var/lib/grafana/dashboards/logs.json
      - grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  loki-data:
  prometheus-data:
  grafana-data:
