# https://prometheus.io/docs/prometheus/latest/configuration/configuration

global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "uptime"
    static_configs:
      - targets: ["uptime:3001"]
    basic_auth:
      username: accepts_any_username
      password: replace_with_uptime_kuma_api_key
